---
title: "Who does more pushups"
author: "Avelyn Potot"
date: "September 22"
output: html_document
---

```{r include=FALSE}
require(knitr)
require(mosaic)
require(tigerstats)
```

<!-- We recommend you use git branches -- create a separate branch for each major section i.e. Introduction, Methods, Results, Inferential Results, and Discussion and Conclusions - leave the YAML block untouched until the final merge where you put in your own name !-->

# Introduction

Several years ago some MAT 111 students who were on the football team conducted a study of their team-mates.  The results are contained in the data frame `pushups` in the `tigerstats` package.

Among other things, the students recorded the type of position a player had on the team (either line or skill), and also the number of push-ups each player could perform in a two-minute period.

Line players are on the offensive or defensive line.  They need to be a certain kind of speed, but they must also be quite big and strong.  Skill players do a lot of running and catching:  they are the quarterback, running backs, receivers, etc.

>We have to identify,classify and analyze our research question and to explain further what tools we use on the data in this question.
OUr research question is:
>Who does more pushups, on average: a line player or a skill player?

# Methods
<!--Decide on your methods:  use "variable analysis" or other appropriate descriptors.  Make sure to choose at least one graphical method and at least one numerical method.!-->

>On this method we will both use graphical method and a numerical method to show our the difference of data which is "pushups".Then we will explain the data that we came up along with graphical data and numerical data.We will also use a different branches for each major section.


# Results
<!--You have both graphical and numerical methods, so you will have both graphical and numerical results to consider.!-->


## Graphical Results
<!--Your graph should have a good title, and axes should be labled as needed.  Discuss your graphical results, showing how they answer the research question.  Use specific features of the graph in your discussion.!-->



## Numerical Results
<!--Numerical results go here. Use the numerical results to describe the patterns if any that exist in the data as focused toward the research question!-->



# Inferential Results
<!--State hypothesis clearly.  Make sure your discussion of the inferential test covers all the aspects that the test output produces, such as test statistic, p-value etc.  Make a decision about the null hypothesis, explain the assumptions on which the selected test/procedure was based, and why the chosen procedure satisfys the assumptions and is appropriate to answer the research question!-->


# Discussion and Conclusion
<!--State your overall conclusion.  This is also a good place to mention other Research Questions that came to mind as you were carrying out this study.!-->

